#!/usr/bin/env python3
"""Generate build-time security key material for QuartzOS kernel."""

from __future__ import annotations

import argparse
import hashlib
import hmac
import os
from pathlib import Path


DEFAULT_ROOT_SECRET = "QuartzOS-BuildRoot-2026"
DEFAULT_BUILD_SALT = "quartzos-build-v1"


def derive_bytes(root_secret: bytes, salt: str, label: str, size: int = 32) -> bytes:
    out = bytearray()
    counter = 0
    while len(out) < size:
        msg = f"{salt}|{label}|{counter}".encode("utf-8")
        out.extend(hmac.new(root_secret, msg, hashlib.sha256).digest())
        counter += 1
    return bytes(out[:size])


def format_array(name: str, data: bytes) -> str:
    cols = []
    for idx, b in enumerate(data):
        cols.append(f"0x{b:02x}")
        if idx != len(data) - 1:
            cols.append(", ")
        if (idx + 1) % 16 == 0 and idx != len(data) - 1:
            cols.append("\n    ")
    joined = "".join(cols)
    return f"static const uint8_t {name}[] = {{\n    {joined}\n}};\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate QuartzOS build-time security key header")
    parser.add_argument("--output", required=True, help="Output header path")
    args = parser.parse_args()

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    root_secret = os.getenv("QOS_BUILD_ROOT_SECRET", DEFAULT_ROOT_SECRET).encode("utf-8")
    build_salt = os.getenv("QOS_BUILD_SALT", DEFAULT_BUILD_SALT)

    derived = {
        "QOS_KEY_LICENSE_HMAC_V2": derive_bytes(root_secret, build_salt, "license.hmac.v2"),
        "QOS_KEY_LICENSE_HMAC_V3": derive_bytes(root_secret, build_salt, "license.hmac.v3"),
        "QOS_KEY_LICENSE_STATE_MAC": derive_bytes(root_secret, build_salt, "license.state.mac"),
        "QOS_KEY_SECURESTORE_ENC": derive_bytes(root_secret, build_salt, "securestore.enc"),
        "QOS_KEY_SECURESTORE_MAC": derive_bytes(root_secret, build_salt, "securestore.mac"),
        "QOS_KEY_SECURESTORE_ENC_PREV": derive_bytes(root_secret, build_salt, "securestore.enc.prev"),
        "QOS_KEY_SECURESTORE_MAC_PREV": derive_bytes(root_secret, build_salt, "securestore.mac.prev"),
        "QOS_KEY_SECURITY_POLICY_SIGN": derive_bytes(root_secret, build_salt, "security.policy.sign"),
        "QOS_KEY_SECURITY_MANIFEST_SIGN": derive_bytes(root_secret, build_salt, "security.manifest.sign"),
        "QOS_KEY_SECURITY_SERVER_PIN": derive_bytes(root_secret, build_salt, "security.server.pin"),
    }

    legacy = {
        "QOS_LEGACY_LICENSE_HMAC_V2": os.getenv(
            "QOS_LEGACY_LICENSE_HMAC_V2",
            "QuartzOS-Licensing-HMAC-Key-V2-2026",
        ).encode("utf-8"),
        "QOS_LEGACY_LICENSE_HMAC_V3": os.getenv(
            "QOS_LEGACY_LICENSE_HMAC_V3",
            "QuartzOS-Licensing-HMAC-Key-V3-2026",
        ).encode("utf-8"),
        "QOS_LEGACY_LICENSE_STATE_MAC": os.getenv(
            "QOS_LEGACY_LICENSE_STATE_MAC",
            "QuartzOS-License-State-MAC-V3-2026",
        ).encode("utf-8"),
        "QOS_LEGACY_SECURESTORE_ENC": os.getenv(
            "QOS_LEGACY_SECURESTORE_ENC",
            "QuartzOS-SecureStore-ENC-V1-2026",
        ).encode("utf-8"),
        "QOS_LEGACY_SECURESTORE_MAC": os.getenv(
            "QOS_LEGACY_SECURESTORE_MAC",
            "QuartzOS-SecureStore-MAC-V1-2026",
        ).encode("utf-8"),
        "QOS_LEGACY_SECURESTORE_MAC_COMPAT": os.getenv(
            "QOS_LEGACY_SECURESTORE_MAC_COMPAT",
            "QuartzOS-SecureStore-ENC-V1-2026",
        ).encode("utf-8"),
    }

    lines = [
        "/* Auto-generated by tools/generate_security_keys.py. */\n",
        "#ifndef GENERATED_SECURITY_KEYS_H\n",
        "#define GENERATED_SECURITY_KEYS_H\n\n",
        "#include <stdint.h>\n\n",
    ]

    for name, value in derived.items():
        lines.append(format_array(name, value))
        lines.append("\n")
    for name, value in legacy.items():
        lines.append(format_array(name, value))
        lines.append("\n")

    lines.append("#endif\n")
    output.write_text("".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
